[tool.poetry]
name = "request"
version = "0.0.1"
description = ""
authors = ["Anderson Rodrgues"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
